### ISSUE TITLE
[To-Do] Feb.2021

### ISSUE THREAD

**Issue by hwaneest** [hwan141592/Python_Fundamentals#1]
- [ ] Organize AIFFEL things -> new repo.
- [ ] update README file
- [ ] write & fix Descriptions
- [ ] PCD(Python Coding Dojang) Keep Going
- [x] Pin.
